#   PCA - LPI

* Με υλικό από το amoeba (https://stats.stackexchange.com/users/28666/amoeba), Making sense of principal component analysis, eigenvectors & eigenvalues, URL (version: 2021-12-03): https://stats.stackexchange.com/q/140579.

---

> Πάνος Λουρίδας, Αναπληρωτής Καθηγητής <br />
> Τμήμα Διοικητικής Επιστήμης και Τεχνολογίας <br />
> Οικονομικό Πανεπιστήμιο Αθηνών <br />
> louridas@aueb.gr

* Ας φανταστούμε ότι έχουμε ένα σύνολο κρασιών.

* Τα κρασιά περιγράφονται από διάφορα χαρακτηριστικά, όπως χρώμα, ποσοστό οινοπνεύματος, οξύτητα, θειώδη, και πολλά άλλα.

* Τώρα έστω ότι επιθυμούμε να μπορούμε να περιγράψουμε κάθε κρασί με *λιγότερα* χαρακτηριστικά.

* Ποια θα ήταν αυτά;

* Θα θέλαμε να βρούμε κάποια χαρακτηριστικά τα οποία από τη μία να διαφέρουν όσο το δυνατόν περισσότερο από κρασί σε κρασί (γιατί αν ένα χαρακτηριστικό είναι το ίδιο σε όλα τα κρασιά, δεν μας λέει τίποτε).

* Επίσης τα χαρακτηριστικά που θα βρούμε θα θέλαμε να απηχούν όσο το δυνατόν περισσότερο τα αρχικά χαρακτηριστικά που έχουμε συγκεντρώσει για κάθε κρασί.

* Δεν είναι απαραίτητο ότι τα χαρακτηριστικά που θα βρούμε είναι υποσύνολο των αρχικών χαρακτηριστικών!

* Τα χαρακτηριστικά αυτά μπορεί να είναι *νέα* χαρακτηριστικά (τα οποία σχετίζονται με τα υπάρχοντα), αλλά όχι κάποια από τα υπάρχοντα.

* Ας φανταστούμε λοιπόν ότι έχουμε μόνο δύο χαρακτηριστικά, τα οποία φαίνονται στην επόμενη εικόνα.

* Τα χαρακτηριστικά είναι δύο διαφορετικές διαστάσεις.

* Κάθε παρατήρησή μας περιγράφεται από ένα ζεύγος συντεταγμένων $(x, y)$ με τις τιμές των δύο διαστάσεων για την παρατήρηση.

* Αν θέλαμε κάθε παρατήρησή μας να περιγράφεται από *μία* και μόνη διάσταση, δηλαδή από *έναν* αριθμό, $z$, ποια θα ήταν αυτή η διάσταση;

<img src="https://i.stack.imgur.com/jPw90.png" />

https://stats.stackexchange.com/a/140579

* Να θυμηθούμε τι επιθυμούμε.

* Θέλουμε η νέα διάσταση που θα βρούμε να είναι τέτοια ώστε τα δεδομένα μας να έχουν τη μεγαλύτερη δυνατή μεταβλητότητα, διακύμανση, σε αυτή.

* Επίσης θέλουμε τα δεδομένα στη νέα διάσταση να απέχουν όσο το δυνατόν λιγότερο από τα δεδομένα στις αρχικές τους διαστάσεις.

* Στην επόμενη εικόνα, μπορούμε να δούμε ποια θα είναι αυτή η διάσταση.

* Περιστρέφοντας τον άξονα που αντιστοιχεί στη νέα αυτή διάσταση, μπορούμε να δούμε ποια είναι η θέση που ικανοποιεί τα κριτήρια που θέσαμε:

  * Στη διαγώνιο που διασχίζει τα δεδομένα, η διακύμανση των προβολών δεδομένων μας (οι κόκκινες τελείες) είναι η μέγιστη δυνατή.
  
  * Επίσης στη διαγώνιο που διασχίζει τα δεδομένα, οι αποστάσεις των προβολών από τα αρχικά δεδομένα (οι κόκκινες γραμμές) είναι οι μικρότερες δυνατές.


<img src="https://i.stack.imgur.com/Q7HIP.gif" />

Πηγή: https://stats.stackexchange.com/a/140579

<img width="500" src="https://upload.wikimedia.org/wikipedia/commons/f/f5/GaussianScatterPCA.svg" />

* Η διαδικασία με την οποία βρίσκουμε αυτές τις νέες διαστάσεις ονομάζεται *Ανάλυση Κύριων Συνιστωσών* (Principal Component Analysis).

* Υπάρχει αποτελεσματικός αλγόριθμος για την εύρεση των συνιστωσών (διαστάσεων) που αναζητούμε.

* Η μέθοδος ανήκει στη μη επιβλεπόμενη Μηχανική Μάθηση, αφού δεν έχουμε ένα σύνολο δεδομένων και λύσεις.

* Έχουμε μόνο ένα σύνολο δεδομένων και τον αριθμό των διαστάσεων που αναζητούμε.

* Εμπίπτει λοιπόν στην κατηγορία της *μείωσης διαστασιμότητας* (dimensionality reduction).

* Για να το δούμε αυτό στην πράξη.

* Να θυμηθούμε τον [δείκτη Αποτελεσματικότητας Λογιστικής Αλυσίδας (Logistic Performance Index indicator, LPI) της Παγκόσμιας Τράπεζας](https://lpi.worldbank.org/).

* Η Παγκόσμια Τράπεζα μετράει, όπως είδαμε, έξι επιμέρους δείκτες.

* Ανταγωνιστικότητα και ποιότητα υπηρεσιών λογιστικής αλυσίδας (Competence and quality of logistics services).

* Συχνότητα με την οποία οι αποστολές παραδίδονται στον προβλεπόμενο χρόνο (Frequency with which shipments reach consignee within scheduled or expected time).

* Ευκολία διαχείρισης ανταγωνιστικά κοστολογημένων αποστολών (Ease of arranging competitively priced shipments).

* Ποιότητα υποδομής εμπορίου και μεταφορών (Quality of trade and transport-related infrastructure).

* Ικανότητα ιχνηλάτησης αποστολών (Ability to track and trace consignments).

* Αποτελεσματικότητα της διαδικασίας εκτελωνισμού (Efficiency of customs clearance process).

* Από αυτούς του έξι επιμέρους δείκτες, συνθέτει έναν ενιαίο δείκτη.

* Πώς προκύπτει ο ενιαίος δείκτης από τους έξι επιμέρους;

* Θα μπορούσε κάποιος να πάρει απλώς το μέσο όρο τους.

* Είναι όμως λογικό αυτό; 

* Για να το δούμε, θα χρησιμοποιήσουμε PCA.

* Πάμε να διαβάσουμε τα στοιχεία του LPI.

In [4]:
import pandas as pd

lpi_df = pd.read_csv("data/International_LPI_2018.csv")
lpi_df

Country   LPI  Customs  Infrastructure  International shipments  \
0         Germany  4.20     4.09            4.37                     3.86   
1          Sweden  4.05     4.05            4.24                     3.92   
2         Belgium  4.04     3.66            3.98                     3.99   
3         Austria  4.03     3.71            4.18                     3.88   
4           Japan  4.03     3.99            4.25                     3.59   
..            ...   ...      ...             ...                      ...   
155  Sierra Leone  2.08     1.82            1.82                     2.18   
156         Niger  2.07     1.77            2.00                     2.00   
157       Burundi  2.06     1.69            1.95                     2.21   
158        Angola  2.05     1.57            1.86                     2.20   
159   Afghanistan  1.95     1.73            1.81                     2.10   

     Logistics quality and competence  Tracking and tracing  Timeliness  
0                                4.31                  4.24        4.39  
1                                3.98                  3.88        4.28  
2                                4.13                  4.05        4.41  
3                                4.08                  4.09        4.25  
4                                4.09                  4.05        4.25  
..                                ...                   ...         ...  
155                              2.00                  2.27        2.34  
156                              2.10                  2.22        2.33  
157                              2.33                  2.01        2.17  
158                              2.00                  2.00        2.59  
159                              1.92                  1.70        2.38  

[160 rows x 8 columns]

* Θα εργαστούμε με τις στήλες που αφορούν τους επιμέρους δείκτες.

In [5]:
lpi_components = [
    'Customs',
    'Infrastructure',
    'International shipments',
    'Logistics quality and competence',
    'Tracking and tracing',
    'Timeliness'
]

lpi_components = lpi_df[lpi_components]
lpi_components

Customs  Infrastructure  International shipments  \
0       4.09            4.37                     3.86   
1       4.05            4.24                     3.92   
2       3.66            3.98                     3.99   
3       3.71            4.18                     3.88   
4       3.99            4.25                     3.59   
..       ...             ...                      ...   
155     1.82            1.82                     2.18   
156     1.77            2.00                     2.00   
157     1.69            1.95                     2.21   
158     1.57            1.86                     2.20   
159     1.73            1.81                     2.10   

     Logistics quality and competence  Tracking and tracing  Timeliness  
0                                4.31                  4.24        4.39  
1                                3.98                  3.88        4.28  
2                                4.13                  4.05        4.41  
3                                4.08                  4.09        4.25  
4                                4.09                  4.05        4.25  
..                                ...                   ...         ...  
155                              2.00                  2.27        2.34  
156                              2.10                  2.22        2.33  
157                              2.33                  2.01        2.17  
158                              2.00                  2.00        2.59  
159                              1.92                  1.70        2.38  

[160 rows x 6 columns]

* Δεδομένου ότι η PCA χρησιμοποιεί τη διακύμανση προκειμένου να εντοπίσει τις διαστάσεις που αναζητούμε, είναι μέθοδος η οποία επιδέχεται (ή χρειάζεται) κανονικοποίηση στα δεδομένα.

In [6]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
lpi_components_standard_scaled = standard_scaler.fit_transform(lpi_components)

* Προχωράμε στο PCA.

* Θέλουμε να κάνουμε PCA για να εντοπίσουμε *μία* συνιστώσα.

In [10]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)

* Εφαρμόζουμε PCA στα δεδομένα μας.

In [11]:
pca.fit(lpi_components_standard_scaled)

PCA(n_components=1)

* Η ιδιότητα `explained_variance_ratio` μας δίνει πόση από τη διακύμανση εξηγεί η συνιστώσα (διάσταση) που υπολογίστηκε. 

* Βλέπουμε ότι εξηγεί πάνω από το 92%!

In [12]:
pca.explained_variance_ratio_

array([0.92257629])

* Στη συνέχεια, μπορούμε να προβάλουμε τα δεδομένα μας πάνω σε αυτήν τη διάσταση.

In [13]:
transformed = pca.transform(lpi_components_standard_scaled)
transformed[:10]

array([[5.54547364],
       [4.93808946],
       [4.86533482],
       [4.81834623],
       [4.81569261],
       [4.79085083],
       [4.69701109],
       [4.68746366],
       [4.65614658],
       [4.58455542]])

* Τι κάνει αυτή η προβολή;

* Η νέα διάσταση που προέκυψε είναι ένας γραμμικός συνδυασμός των υπαρχόντων.

* Οι συντελεστές του γραμμικού συνδυασμού δίνονται από την ιδιότητα `components_`.

* Οι συντελεστές των κυρίων συνιστωσών ονομάζονται *φορτία* (loadings).

In [14]:
pca.components_

array([[0.40728498, 0.41303479, 0.39604297, 0.41660675, 0.41067906,
        0.40552768]])

* Έτσι, αν έχουμε τους έξι επιμέρους δείκτες (διαστάσεις), η νέα διάσταση προκύπτει από τη σχέση:

$$ 0{,}40728498 x_1 + 0{,}41303479 x_2 + 0{,}39604297 x_3 + 0{,}41660675 x_4 + 0{,}41067906 x_5 + 0{,}40552768 x_6 $$

* Επομένως θα μπορούσαμε να χρησιμοποιήσουμε την τιμή `transformed` ως τον δείκτη LPI.

* Πλην όμως αυτή δεν κυμαίνεται από το 1 έως και το 5.

In [9]:
print(transformed.min(), transformed.max())

-3.816178904589358 5.545473639886474


* Μπορούμε να ξεπεράσουμε το πρόβλημα αν σκεφτούμε ότι μπορούμε να χρησιμοποιήσουμε τα φορτία για να υπολογίσουμε τον σταθμισμένο μέσο όρο των επιμέρους δεικτών.

* Πράγματι, οι τιμές που παίρνουμε είναι πολύ κοντά στις τελικές τιμές του LPI που δημοσιεύει η Παγκόσμια Τράπεζα.

In [15]:
import numpy as np

np.average(lpi_components, axis=1, weights=pca.components_[0])[:10]

array([4.2122752 , 4.05869046, 4.03685368, 4.03281921, 4.03928615,
       4.03042283, 4.00731942, 4.00371973, 3.99503935, 3.98022523])

* Τι καταφέραμε;

* Πήγαμε από τις έξι διαστάσεις σε μία.

* Γενικότερα, μπορούμε να έχουμε πολλές περισσότερες διαστάσεις και να θέλουμε να τις μειώσουμε:

  * Επειδή οι διαστάσεις είναι περισσότερες από όσες μπορούμε να χειριστούμε.
  
  * Επειδή οι διαστάσεις μπορεί να είναι περιττές (θόρυβος).
  
  * Επειδή με λιγότερες διαστάσεις μπορούμε να κατανοήσουμε τα προβλήματά μας καλύτερα.
  
* Αλλά προσοχή: είναι δική μας δουλειά η ερμηνεία των νέων διαστάσεων!